language: ruby
rvm:
- 2.1.1
- 2.0.0
- 1.9.3
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: aue9Co0K9XVWtwRNSilPrJ7B31PAFe1MoBgp8M6qt2/Ssr+1fFxAB/7ZEtjyWbanYWZMGEFyflUnR0GBA8WMrld64k3hkAwgpOo2anmuwcN9jDTpFPsQ63/0aEfuo761Dg3CmflsZIHzw+wVY9NAEAVSmm+juDM3JudyVzZ/EPM=
  gem: berks2env
  on:
    tags: true
    repo: petecheslock/berks2env
