language: ruby
rvm:
- 2.1.1
- 1.9.3
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: bDOj3IJ0kZWKvLTb4c/Y9for/QPttyhGJBKr89Rhx6D1iAFahOFf09Md25CjymaC91tVdXoRgI1lTiyi1EYSJx0VF5Rk/wNjHT3vIBBVsnZtNE+lSkKfgd0qhh7Xt/YQbVxXFxlkVNJhiNf72QuESRwb9d/MPoz+5Wmje3KX9kM=
  gemspec: berks2env.gemspec
  on:
    tags: true
    rvm: 2.1.1
    repo: petecheslock/berks2env
